### ISSUE TITLE
lower-level API

### ISSUE THREAD

**Issue by mattdesl** [Jam3/gh-api-stream#2]
its a bit clunky to use this for one-off calls like readme or contents. 

would be nice to have a lower level callback based API that lives in its own module. it would not deal with pagination. it can also be optimized for a very small browser footprint using `xhr` instead of `got`.

same setup as:
- https://github.com/mattdesl/marvel-comics-api
- https://github.com/mattdesl/marvel-comics-api-stream

**Comment by tunnckoCore** [comment]
conceptually idea is good. but given libs are totally no logical. ;d

Just side comment on both libs
in `*-stream` you use `through2` to create empty stream (which is pretty slow process and btw that's the reason why gulp core (glob-stream) is so damn slow) and then use the async api, instead of just create one module that will inherit nature of `got` - if not cb so stream (before v4). `got` have streaming api, there's no reason to create stream form `through`. :)

**Comment by mattdesl** [comment]
> but given libs are totally no logical 

Hmm, what do you mean?

> and then use the async api, instead of just create one module that will inherit nature of got

I can't return the `got` stream since these modules need to span multiple requests. I would be interested in seeing how you think these modules could be improved/optimized without `through2`, though.

**Comment by mattdesl** [comment]
This now exists, and its 9kb in the browser:
https://github.com/Jam3/gh-api
